// Generated by CoffeeScript 1.3.3
(function() {

  window.Processor8080Compiler = {
    compile: function(memory, entryPoint) {
      var a, addr, addrs, dest, destinations, i, opcode, unvisitedAddresses, visitedAddresses, _i, _j, _len;
      unvisitedAddresses = {};
      visitedAddresses = {};
      unvisitedAddresses[entryPoint] = true;
      while (true) {
        addr = null;
        for (a in unvisitedAddresses) {
          addr = parseInt(a);
          break;
        }
        if (addr === null) {
          break;
        }
        delete unvisitedAddresses[addr];
        visitedAddresses[addr] = true;
        opcode = OPCODES[memory.read(addr)];
        destinations = opcode.destinations(memory, addr);
        for (_i = 0, _len = destinations.length; _i < _len; _i++) {
          dest = destinations[_i];
          if (!(dest in visitedAddresses)) {
            unvisitedAddresses[dest] = true;
          }
        }
      }
      addrs = [];
      for (i = _j = 0; 0 <= 0x10000 ? _j < 0x10000 : _j > 0x10000; i = 0 <= 0x10000 ? ++_j : --_j) {
        if (i in visitedAddresses) {
          addrs.push(i);
        }
      }
      return console.log(addrs);
    }
  };

}).call(this);
